### ISSUE TITLE
Issue with Vectorizing Custom Mujoco Environment in "make_vec_env()"

### ISSUE THREAD

**Issue by muslim-adedamola** [denisgriaznov/CustomMuJoCoEnviromentForRL#2]
I’m encountering an issue when trying to vectorize the ball_balance_env custom environment that inherits from MujocoEnv using the **make_vec_env() function from stable_baselines3.common.env_util.**

Despite the custom environment inheriting from MujocoEnv, which in turn inherits from gymnasium.Env, the make_vec_env() function throws an assertion error stating that the environment should directly inherit from gymnasium.Env.

"**Error Message: AssertionError: Your environment must inherit from the gymnasium.Env class cf. https://gymnasium.farama.org/api/env/"**

I tried to solve this by writing a gym environment that wraps the custom mujoco environment but the error persists. Could you suggest any modifications needed to ensure compatibility with **make_vec_env()**?

**Comment by denisgriaznov** [comment]
Thanks for your comment. I changed some versions of packages, checked and it works (though I think it should have worked initially with the recommended versions). I added a script with examples of vectorized environment:
https://github.com/denisgriaznov/CustomMuJoCoEnviromentForRL/blob/master/vec_env_learn.py
Also, instead of specifying individual packages, I added a requirements file, before running, make sure that all packages have the required versions or install them into the virtual environment from scratch via
`pip install -r requirements.txt`

**Comment by muslim-adedamola** [comment]
> Thanks for your comment. I changed some versions of packages, checked and it works (though I think it should have worked initially with the recommended versions). I added a script with examples of vectorized environment: https://github.com/denisgriaznov/CustomMuJoCoEnviromentForRL/blob/master/vec_env_learn.py Also, instead of specifying individual packages, I added a requirements file, before running, make sure that all packages have the required versions or install them into the virtual environment from scratch via `pip install -r requirements.txt`

I just git cloned the update and tested it. The same Assertion Error was raised. 

Apparently, I discovered the check_env() method works and checks single environment and not vectorized environment (I guess this is due to the way it works and handles environment). Thank you so much.
